### ISSUE TITLE
镜像无法运行

### ISSUE THREAD

**Issue by turingking** [chariothy/dnspod-ddns#1]
以下是日志
```Traceback (most recent call last):
File "main.py", line 3, in <module>
from util import show_diff, CONFIG, APP
File "/usr/src/app/util.py", line 56, in <module>
checkConfig()
File "/usr/src/app/util.py", line 28, in checkConfig
from config import CONFIG
File "/usr/src/app/config.py", line 96
'server_port': 7788 # DDNS server 端口
^
SyntaxError: invalid syntax```

**Comment by chariothy** [comment]
可能是之前push之后触发了编译docker， docker pull最新版就可以了。
